- name: Create swap memory
  hosts: webserver
  become: yes

  vars:
    swap_file: /swapfile
    swap_size: 2G

  tasks:
    - name: Check existing swap
      command: swapon --show
      register: swap_status
      ignore_errors: yes

    - name: Create swap file if not exists
      command: fallocate -l {{ swap_size }} {{ swap_file }}
      args:
        creates: "{{ swap_file }}"
      when: swap_status.stdout == ""

    - name: Set swap permissions
      file:
        path: "{{ swap_file }}"
        mode: '0600'
      when: swap_status.stdout == ""

    - name: Setup swap area
      command: mkswap {{ swap_file }}
      when: swap_status.stdout == ""

    - name: Enable swap
      command: swapon {{ swap_file }}
      when: swap_status.stdout == ""

    - name: Persist swap in fstab
      mount:
        name: none
        src: "{{ swap_file }}"
        fstype: swap
        opts: sw
        state: present
      when: swap_status.stdout == ""
